{% set name = "pyglm" %}
{% set version = "2.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyglm-{{ version }}.tar.gz
  sha256: b4847b0b60888b5c649b17b0a72d1f3f1ee07086cd5f431a7d977fad3cdbadab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - glm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Zuzu-Typ/PyGLM
  summary: OpenGL Mathematics library for Python
  license: Zlib
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
